// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSIXRmJaNPmpjKuHM_sBZwyt7sYPx8ODo',
    appId: '1:378775177061:web:7cb58a16dcf22a1d46838c',
    messagingSenderId: '378775177061',
    projectId: 'battery-aadhar',
    authDomain: 'battery-aadhar.firebaseapp.com',
    storageBucket: 'battery-aadhar.firebasestorage.app',
    measurementId: 'G-3JPQ80P4GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCEG0WAGeDLf3TOrP6dFWu9NEChjbBlw',
    appId: '1:378775177061:android:f61d5d388b89f0c246838c',
    messagingSenderId: '378775177061',
    projectId: 'battery-aadhar',
    storageBucket: 'battery-aadhar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVd_sSr7Koi9H2Pj5yEztnIu36DGB1rnA',
    appId: '1:378775177061:ios:4d937988adbc887946838c',
    messagingSenderId: '378775177061',
    projectId: 'battery-aadhar',
    storageBucket: 'battery-aadhar.firebasestorage.app',
    iosBundleId: 'com.example.batteryAadhaarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVd_sSr7Koi9H2Pj5yEztnIu36DGB1rnA',
    appId: '1:378775177061:ios:4d937988adbc887946838c',
    messagingSenderId: '378775177061',
    projectId: 'battery-aadhar',
    storageBucket: 'battery-aadhar.firebasestorage.app',
    iosBundleId: 'com.example.batteryAadhaarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSIXRmJaNPmpjKuHM_sBZwyt7sYPx8ODo',
    appId: '1:378775177061:web:bcc7cc4450e5503246838c',
    messagingSenderId: '378775177061',
    projectId: 'battery-aadhar',
    authDomain: 'battery-aadhar.firebaseapp.com',
    storageBucket: 'battery-aadhar.firebasestorage.app',
    measurementId: 'G-J8ERCND5HZ',
  );
}
